pipeline {
    // Configure global agent
    agent {
        docker {
            image 'maven:3.8.1-openjdk-17'
            args '-v /var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar-scanner:/opt/sonar-scanner'
        }
    }

    // Define Build Stages
    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/iam-veeramalla/Jenkins-Zero-To-Hero.git',
                    branch: 'main'
            }
        }
        stage('Build Artifacts') {
            steps {
                sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app \
                    && mvn clean package'
            }
        }
        stage('Code Quality Check') {
            environment {
                SONAR_URL = 'http://159.89.239.109:9000'
                SONAR_HOME = '/opt/sonar-scanner'
            }
            steps {
                withSonarQubeEnv('sonar-scanner') {
                    withCredentials([string(credentialsId: 'sonar-scanner', variable: 'SONAR_AUTH_TOKEN')]) {
                        script {
                            sh "cd java-maven-sonar-argocd-helm-k8s/spring-boot-app \
                            && $SONAR_HOME/bin/sonar-scanner -Dsonar.login=$SONAR_AUTH_TOKEN \
                                -Dsonar.host.url=${SONAR_URL} \
                                -Dsonar.projectKey=DevOps-CICD"
                        }
                    }
                }
            }
        }
    }
}