apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-boot-deployment
    labels:
        app: middleware
spec:
    replicas: 2
    selector:
        matchLabels:
            app: middleware
    template:
        metadata:
            labels:
                app: middleware
        spec:
            containers:
                - name: spring-boot-container
                  image: ashuprasaddocker/cicddevops:v52
                  ports:
                    - containerPort: 8080