apiVersion: v1
kind: Service
metadata:
    name: spring-boot-service
    labels:
        app: middleware
spec:
    selector:
        app: middleware
    type: NodePort
    ports:
        - port: 80
          targetPort: 8080
          nodePort: 31000